#!/usr/bin/env php
<?php

/**
 * CLI application entry point.
 *
 * @since 2020-05-07
 * @author Danny Damsky <dannydamsky99@gmail.com>
 */

ini_set('memory_limit', '128M');
ini_set('max_execution_time', '30');
ini_set('disable_functions', '');

try {
    require_once __DIR__ . DIRECTORY_SEPARATOR . 'bootstrap.php';

    // Start the application.
    $application->start($argc, $argv);
} catch (Throwable $e) {
    echo "\n{$e->getMessage()}\n\n{$e->getTraceAsString()}\n\n";
    exit(1);
}

exit(0);